# Generated by Django 5.1.1 on 2024-10-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='imageUrl',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
