# Generated by Django 5.1.1 on 2024-10-23 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)]),
            preserve_default=False,
        ),
    ]
